### ISSUE TITLE
About_tab hover

### ISSUE THREAD

**Issue by portala** [Portal-A/portal-a#27]
Let's remove the black line below for now so we're consistent with the work page.

<img width="723" alt="screen shot 2018-06-05 at 5 06 27 pm" src="https://user-images.githubusercontent.com/37456166/41008962-f8394238-68e2-11e8-856a-6cf59d355549.png">

**Comment by kpettinga** [comment]
@portala I added that black line as a loading indicator because the content for these pages are fetched dynamically with javascript. There needs to be some kind of indication to the user that content retrieval is in progress, otherwise the experience just feels slow and/or broken. It will take some users longer to load content than others.

If you want some kind of different indication for loading, we can figure that out.

**Comment by portala** [comment]
@kpettinga i see, thanks for explaining! in that case, can we make the line blue to be consistent with the main nav?
